# Generated by Django 4.0.5 on 2022-06-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['institution_id'],
            },
        ),
    ]
